version: 2
updates:
  # GatewayAPI Python dependencies (Poetry)
  - package-ecosystem: "pip"
    directory: "/microservices/gatewayApi"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    versioning-strategy: "lockfile-only"  # This is important for Poetry projects
    labels:
      - "dependencies"
      - "python"
    allow:
      # Allow both direct and indirect updates for all packages
      - dependency-type: "all"

  # Docker dependencies for GatewayAPI
  - package-ecosystem: "docker"
    directory: "/microservices/gatewayApi"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "docker"