openapi: 3.0.0
info:
  title: Sample API
  description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
  version: 0.0.1
servers:
  - url: https://api.example.com/v1
    description: Optional server description, e.g. Main (production) server
  - url: http://staging-api.example.com
    description: Optional server description, e.g. Internal staging server for testing
paths:
  /headers:
    get:
      summary: Returns the request headers that the upstream receives.
      description: Optional extended description in CommonMark or HTML.
      responses:
        '200':    # status code
          description: A JSON object of request header name and values
          content:
            application/json:
              schema: 
                type: object
