[tool.poetry]
name = "gwa-api"
version = "1.0.0"
package-mode = false
description = "Gateway API for multi-tenant configuration on Kong API Gateway"
authors = []

[tool.poetry.dependencies]
python = "^3.11"
werkzeug = "3.1.3"
ply = "3.11"
cryptography = "43.0.3"
authlib = "1.4.1"
flask-swagger-ui = "3.36.0"
Jinja2 = "3.1.5"
PyYAML = "6.0.2"
munch = "2.5.0"
boto3 = "1.36.22"
flask = "2.3.3"
flask-compress = "1.17"
flask-cors = "4.0.2"
gevent = "23.9.1"
# greenlet = "2.0.2"
gunicorn = "22.0.0"
python-keycloak = "0.29.1"
requests = "^2.32"
flask-jwt-simple = "0.0.3"

[tool.poetry.dev-dependencies]
autopep8 = "^1.5.7"
pycodestyle = "2.12.1"
pylint = "3.3.4"
python-dotenv = "^0.21.0"
pytest = "^8.2.0"
pytest-cov = "^5.0.0"
pytest-mock = "^3.14.0"

[tool.coverage.run]
relative_files = true
omit = [
    "tests"
]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
