openapi: 3.0.0
info:
  title: Sample API
  description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
  version: 0.0.1
servers:
  - url: https://httpbin.org
    description: The upstream service
paths:
  "/headers":
    get:
      summary: Returns the request headers that the upstream receives.
      description: Optional extended description in CommonMark or HTML.
      responses:
        '200':    # status code
          description: A JSON object of request header name and values
          content:
            application/json:
              schema: 
                type: object
