name: Sync GitHub issues to Jira
on: [issues, issue_comment]

jobs:
  sync-issues:
    name: Sync issues to Jira
    runs-on: ubuntu-24.04
    steps:
      - uses: ikethecoder/sync-issues-github-jira@dev
        with:
          webhook-url: ${{ secrets.JIRA_WEBHOOK_URL }}

  cleanup-runs:
    name: Delete workflow runs
    runs-on: ubuntu-latest
    permissions:
      actions: write    
    steps:
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@feeb82053ea847a97fe4ee2aa314c94eac0eff04 # v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 1
          keep_minimum_runs: 5
          delete_workflow_pattern: jira.yaml
