name: Draft release from master

on:
  push:
    branches:
      - master

jobs:
  release-on-push:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - id: release
        uses: rymndhng/release-on-push-action@v0.24.0
        with:
          bump_version_scheme: patch

      - name: Check Output Parameters
        run: |
          echo "Got tag name ${{ steps.release.outputs.tag_name }}"
          echo "Got release version ${{ steps.release.outputs.version }}"

      - name: Create gwa-api docker image related to the release
        uses: docker/build-push-action@v1
        with:
          registry: docker.pkg.github.com
          username: $GITHUB_ACTOR
          password: ${{ secrets.GITHUB_TOKEN }}
          repository: bcgov/gwa-api/gwa-gateway-api
          path: microservices/gatewayApi
          dockerfile: microservices/gatewayApi/Dockerfile
          push: true
          tags: ${{ steps.release.outputs.tag_name }}
          tag_with_sha: false

      - name: Create gwa-kube-api docker image related to the release
        uses: docker/build-push-action@v1
        with:
          registry: docker.pkg.github.com
          username: $GITHUB_ACTOR
          password: ${{ secrets.GITHUB_TOKEN }}
          repository: bcgov/gwa-api/gwa-kube-api
          path: microservices/kubeApi
          dockerfile: microservices/kubeApi/Dockerfile
          push: true
          tags: ${{ steps.release.outputs.tag_name }}
          tag_with_sha: false

      - name: Create gwa-scheduler docker image related to the release
        uses: docker/build-push-action@v1
        with:
          registry: docker.pkg.github.com
          username: $GITHUB_ACTOR
          password: ${{ secrets.GITHUB_TOKEN }}
          repository: bcgov/gwa-api/gwa-scheduler
          path: microservices/gatewayJobScheduler
          dockerfile: microservices/gatewayJobScheduler/Dockerfile
          push: true
          tags: ${{ steps.release.outputs.tag_name }}
          tag_with_sha: false
