name: Draft release from master

on:
  push:
    branches:
      - master

jobs:
  release-on-push:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0
      - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5
        with:
          python-version: "3.13"
      - name: Install deps
        run: |
          sudo apt update
          sudo apt install -y pipx git
          pipx ensurepath
          pipx install poetry

      - name: Test coverage for Gateway API
        run: |
          export PATH=/root/.local/bin:$PATH
          cd microservices/gatewayApi
          poetry env use 3.11
          poetry install --no-root --no-cache
          ENV=test GITHASH=11223344 \
          poetry run coverage run --branch -m pytest -s -v
          poetry run coverage xml

      - name: Test coverage for Scheduler API
        run: |
          export PATH=/root/.local/bin:$PATH
          cd microservices/gatewayJobScheduler
          poetry install --no-root
          SYNC_INTERVAL=1000 \
          DATA_PLANE=test-dp \
          poetry run coverage run --branch -m pytest -s -v
          poetry run coverage xml

      - name: Test coverage for Kube API
        run: |
          export PATH=/root/.local/bin:$PATH
          cd microservices/kubeApi
          poetry install --no-root
          ACCESS_USER=kubeuser ACCESS_SECRET=s3cret \
          poetry run coverage run --branch -m pytest -s -v
          poetry run coverage xml

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - id: release
        uses: rymndhng/release-on-push-action@aebba2bbce07a9474bf95e8710e5ee8a9e922fe2 # v0.28.0
        with:
          bump_version_scheme: patch

      - name: Check Output Parameters
        run: |
          echo "Got tag name ${{ steps.release.outputs.tag_name }}"
          echo "Got release version ${{ steps.release.outputs.version }}"

      - name: Create gwa-api docker image related to the release
        uses: docker/build-push-action@3e7a4f6646880c6f63758d73ac32392d323eaf8f # v1
        with:
          registry: docker.pkg.github.com
          username: $GITHUB_ACTOR
          password: ${{ secrets.GITHUB_TOKEN }}
          repository: bcgov/gwa-api/gwa-gateway-api
          path: microservices/gatewayApi
          dockerfile: microservices/gatewayApi/Dockerfile
          push: true
          tags: ${{ steps.release.outputs.tag_name }}
          tag_with_sha: false

      - name: Create gwa-kube-api docker image related to the release
        uses: docker/build-push-action@3e7a4f6646880c6f63758d73ac32392d323eaf8f # v1
        with:
          registry: docker.pkg.github.com
          username: $GITHUB_ACTOR
          password: ${{ secrets.GITHUB_TOKEN }}
          repository: bcgov/gwa-api/gwa-kube-api
          path: microservices/kubeApi
          dockerfile: microservices/kubeApi/Dockerfile
          push: true
          tags: ${{ steps.release.outputs.tag_name }}
          tag_with_sha: false

      - name: Create gwa-scheduler docker image related to the release
        uses: docker/build-push-action@3e7a4f6646880c6f63758d73ac32392d323eaf8f # v1
        with:
          registry: docker.pkg.github.com
          username: $GITHUB_ACTOR
          password: ${{ secrets.GITHUB_TOKEN }}
          repository: bcgov/gwa-api/gwa-scheduler
          path: microservices/gatewayJobScheduler
          dockerfile: microservices/gatewayJobScheduler/Dockerfile
          push: true
          tags: ${{ steps.release.outputs.tag_name }}
          tag_with_sha: false
