name: 'Send review reminders'
on:
  schedule:
    - cron: '30 1 * * 1-5' # Scheduled to run at 1:30 AM, Monday through Friday
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  remind:
    runs-on: ubuntu-latest
    steps:
      - uses: bcgov/aps-devops/pr-reminder@dev

